name: Merge y pruebas automáticas

on:
  push:
    branches: [rama]  # Ignorar ramas main, desarrollo y release

jobs:
  detect-keyword-and-merge:
    name: Actualizar rama y ejecutar pruebas
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    permissions: write-all
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2
    - name: Verificar si el commit contiene la palabra clave
      id: check-keyword
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "El mensaje del commit es: $COMMIT_MESSAGE"
        if [[ "$COMMIT_MESSAGE" != *"#merge"* ]]; then
          echo "La palabra clave merge no fue encontrada en el commit. Abortando."
          exit 0
        fi
          echo "La palabra clave merge  fue encontrada en el commit.."
    - name: Configuración de entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Merge de la rama desarrollo a feature
      if: ${{ success() }}
      run: |
        git config user.name "$(git log -1 --pretty=format:'%an')"  # Recupera el nombre del autor del último commit
        git config user.email "$(git log -1 --pretty=format:'%ae')"  # Recupera el correo del autor del último commit
        git fetch origin
        git checkout dev
        git pull
        git checkout ${{ github.ref_name }}
        git merge origin/dev --allow-unrelated-histories
    - name: Ejecutar pruebas unitarias
      run: |
        pip install -r requirements.txt
        python -m unittest discover tests
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      # run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
      run: echo "{name}={MENSAJE_ERROR}" >> $GITHUB_OUTPUT
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      # run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
      run: echo "{name}={MENSAJE_EXITO}" >> $GITHUB_OUTPUT
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m

    - name: Hacer merge de feature a desarrollo si las pruebas pasan
      if: ${{ success() }}
      run: |
        git config user.name "$(git log -1 --pretty=format:'%an')"  # Recupera el nombre del autor del último commit
        git config user.email "$(git log -1 --pretty=format:'%ae')"  # Recupera el correo del autor del último commit
        git fetch origin
        git checkout dev
        git pull
        git merge ${{ github.ref_name }} --allow-unrelated-histories
        git push origin dev