name: Merge y pruebas automáticas

on:
  push:
    branches: [rama]  # Ignorar ramas main, desarrollo y release

jobs:
  detect-keyword-and-merge:
    name: Actualizar rama y ejecutar pruebas
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2
    - name: Verificar si el commit contiene la palabra clave
      id: check-keyword
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "El mensaje del commit es: $COMMIT_MESSAGE"
        if [[ "$COMMIT_MESSAGE" != "#merge" ]]; then
          echo "La palabra clave #merge no fue encontrada en el commit. Abortando."
          exit 0
        fi

    - name: Configuración de entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Merge de la rama desarrollo a feature
      run: |
        git config user.name "$(git log -1 --pretty=format:'%an')"  # Recupera el nombre del autor del último commit
        git config user.email "$(git log -1 --pretty=format:'%ae')"  # Recupera el correo del autor del último commit
        git checkout dev
        git pull
        git checkout ${{ github.ref_name }}
        git fetch origin
        git merge origin/dev || exit 1  # Si falla el merge, se detiene

    - name: Ejecutar pruebas unitarias
      run: |
        pip install -r requirements.txt
        python -m unittest discover tests
      continue-on-error: false

    - name: Hacer merge de feature a desarrollo si las pruebas pasan
      if: success()
      run: |
        git checkout dev
        git merge ${{ github.ref_name }}
        git push origin dev